# Generated by Django 3.1.1 on 2020-10-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20201018_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followercnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='followingcnt',
            field=models.IntegerField(default=0),
        ),
    ]
